baseURL = 'https://quinteirosm.labveiltec.ch/'
languageCode = 'fr-ch'
title = 'LabVeilTec - quinteirosm'
theme = 'github-style-plus'

[params]
  description = "More espresso, less depresso â˜•"
  github = "quinteirosm"
  enableGithubFollowers = true
  twitter = ""
  linkedin = "miguelquinteiros"
  email = "quinteiros.m@gmail.com"
  stackoverflow=""
  lastmod = true
  userStatusEmoji = "ğŸ˜´"
  favicon = "https://avatars.githubusercontent.com/u/50415792?v=4"
  avatar = "https://avatars.githubusercontent.com/u/50415792?v=4"
  location = "Switzerland"
  enableGitalk = false
  rss = false
  enableLocalSearch = true
  sponsorLink = "https://www.paypal.me/miigou" 
  gtmId = "your gtm id"
    
  [params.gitalk]
    accessToken = "Your Github access token" # Generate token from github settings  
    repo = "quinteirosm.github.io" # ä½ è¦ç”¨ä¾†å­˜æ”¾ issue çš„ repo åå­—(ä¸ä¸€å®šè¦æ˜¯ä½ çš„ github page repo)
    owner = "quinteirosm" # ä½ çš„GitHub ID
    admin = "quinteirosm" # ä½ çš„GitHub ID
    id = "location.pathname" # æ–‡ç« é é¢çš„é€£çµå°±æ˜¯ID
    labels = "gitalk" # Github issue labels. If you used to use Gitment, you can change it
    perPage = 15 # Pagination size, with maximum 100.
    pagerDirection = "last" # Comment sorting direction, available values are 'last' and 'first'.
    createIssueManually = true # è¨­ç½®ç‚ºtrueï¼Œå¦‚æœæ˜¯ç®¡ç†å“¡ç™»éŒ„ï¼Œæœƒè‡ªå‹•å‰µå»ºissueï¼Œå¦‚æœæ˜¯falseï¼Œéœ€è¦ç®¡ç†å“¡æ‰‹å‹•æ·»åŠ ç¬¬ä¸€å€‹è©•è«–(issue)
    distractionFreeMode = false # Enable hot key (cmd|ctrl + enter) submit comment.    
    proxy = "https://cors-anywhere.azm.workers.dev/https://github.com/login/oauth/access_token" # å¯ä»¥è‡ªè¡Œæ·»åŠ åå‘ä»£ç†

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]
